"""
reasoning/narrative.py — template-assembled narrative (Sherr-I Reasoning Engine).

Pure, deterministic, stdlib-only. Every sentence is built from real fields by string
template — never generated by an LLM, so it cannot hallucinate a fact that isn't in
the data.

LANGUAGE CONTRACT (enforced by tests):
  allowed  : moved / rose / fell / coverage aligns with / connected to / preceded /
             observed / co-moved
  forbidden: will, causes, caused, predict, expect, forecast, should, and "impact"
             used as a forward claim
"""

from __future__ import annotations

import re

# Words that would turn an observation into a causal or forward-looking claim.
FORBIDDEN = [
    "will ", "causes", "caused", "causing", "predict", "prediction", "forecast",
    "expect", "expected to", "should ", "going to", "likely to", "set to",
    "poised to", "impact on", "due to",
]

# Terms that would turn intelligence into INVESTMENT ADVICE. Under SEBI's investment
# adviser regulations, telling a reader what to do with their money is a regulated
# activity; describing an observed market condition is not. These are matched on word
# boundaries so "buyer", "sells", "targeting" in a headline cannot trip the guard,
# while the bare imperative does.
FORBIDDEN_ADVICE = [
    "buy", "sell", "hold", "invest", "invests", "investing", "recommend",
    "recommends", "recommended", "recommendation", "advice", "advise", "target",
    "targets", "allocate", "allocation", "portfolio", "position", "entry", "exit",
    "stop loss", "stoploss", "upside", "downside", "undervalued", "overvalued",
    "bullish", "bearish", "rally", "correction", "opportunity",
]

# Any explicit price level reads as a target even without the word.
PRICE_TARGET_RE = re.compile(
    r"(?:₹|rs\.?|inr|\$|usd)\s?\d[\d,]*(?:\.\d+)?|\b\d[\d,]*(?:\.\d+)?\s?(?:₹|rs\b|inr\b)",
    re.IGNORECASE)

# Shown on every card. Not decoration — it is the line that keeps a description of
# market conditions from being read as a recommendation.
DISCLAIMER = "SherrByte provides market intelligence, not investment advice."


def move_words(direction: int) -> str:
    """Neutral verb for a market move."""
    return "rose" if direction > 0 else "fell" if direction < 0 else "was flat"


def signed_pct(pct: float, direction: int) -> str:
    sign = "+" if direction > 0 else "-" if direction < 0 else ""
    return f"{sign}{abs(pct):.2f}%"


def confidence_word(conf: float) -> str:
    # Bands chosen so 0.78 reads "moderate" — well-evidenced but not conclusive.
    if conf >= 0.80:
        return "high"
    if conf >= 0.5:
        return "moderate"
    if conf >= 0.3:
        return "limited"
    return "low"


# Beyond this the window is called out as wide in the card itself.
WIDE_WINDOW_HOURS = 48


def window_phrase(hours: int) -> str:
    """'36h' but '3 days' — 168h is technically correct and humanly useless."""
    hours = int(hours or 0)
    if hours >= 48 and hours % 24 == 0:
        d = hours // 24
        return f"{d} day{'' if d == 1 else 's'}"
    return f"{hours}h"


def _join(items: list[str], limit: int = 3) -> str:
    """Human list: 'a, b and c' (capped)."""
    items = [i for i in items if i][:limit]
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def build_narrative(r: dict, *, concise: bool = False) -> str:
    """Assemble the reasoned narrative from a reasoned_insight dict.

    Only sections with real data contribute a sentence — a thin window produces a
    short honest narrative rather than padded filler.
    """
    focal = r.get("focal") or {}
    parts: list[str] = []

    # 1. THE MOVE (or the news spike, when news is focal)
    if focal.get("type") == "market_move":
        inst = focal.get("instrument", "An instrument")
        cls = focal.get("asset_class")
        pct = signed_pct(float(focal.get("move_pct") or 0.0), int(focal.get("direction") or 0))
        cls_txt = f" ({cls})" if cls else ""
        parts.append(f"{inst}{cls_txt} {move_words(int(focal.get('direction') or 0))} {pct}.")
    else:
        ents = _join(focal.get("entities") or [])
        parts.append(f"Coverage of {ents or 'these entities'} rose sharply.")

    # 2. THE NEWS BEHIND IT
    links = r.get("news_link") or []
    if links:
        articles = sum(int(l.get("article_count") or 0) for l in links)
        sources = max((int(l.get("source_count") or 0) for l in links), default=0)
        # Every link carries the same connected-entity list, so flattening without
        # dedup repeats names ("covered Reliance, Nifty and Reliance").
        topics = _join(list(dict.fromkeys(
            t for l in links for t in (l.get("entities") or []))))
        window = int(r.get("window_hours", 24) or 24)
        parts.append(
            f"In the preceding {window_phrase(window)}, "
            f"{articles} article{'' if articles == 1 else 's'} "
            f"across {sources} source{'' if sources == 1 else 's'} covered "
            f"{topics or 'related entities'}.")
        # A wide window finds more overlap but says less about sequence. Disclose it
        # in the card rather than letting "preceding 7 days" read as tight timing.
        if window > WIDE_WINDOW_HOURS:
            parts.append(f"That is a wide window — proximity over "
                         f"{window_phrase(window)} is weaker evidence of sequence "
                         f"than a same-day link.")

    # 3. CROSS-MARKET (the multi-asset payoff)
    cross = r.get("cross_market") or []
    if cross:
        movers = _join([f"{c.get('instrument')} {signed_pct(float(c.get('move_pct') or 0.0), int(c.get('direction') or 0))}"
                        for c in cross])
        n = len(cross) + 1
        parts.append(f"This coverage also aligns with {movers} — a pattern observed "
                     f"across {n} market{'' if n == 1 else 's'}.")

    # 3b. LAG EVIDENCE (M2) — only stated when the guards actually passed.
    # Concise mode is for Tier 1 observation cards, which by definition have no
    # history: the lag, connected-entity and historical sentences would all be
    # "nothing to report", so they are dropped rather than padded.
    lag = {} if concise else (r.get("lag") or {})
    if lag.get("passed"):
        d = int(lag.get("lag") or 0)
        when = "the same day" if d == 0 else f"about {d} day{'' if d == 1 else 's'} ahead"
        parts.append(f"Across {lag.get('buckets')} days of history, coverage of these "
                     f"entities has moved {when} of this instrument "
                     f"(rank correlation {lag.get('rho')}).")

    # 4. CONNECTED ENTITIES
    connected = [] if concise else (r.get("connected") or [])
    if connected:
        # M4 — name the structurally central entity when centrality is available.
        ranked = [c for c in connected if c.get("centrality") is not None]
        central = max(ranked, key=lambda c: c["centrality"])["entity"] if ranked else None
        line = f"Connected to: {_join([c.get('entity') for c in connected], 4)}"
        parts.append(f"{line} (most central: {central})." if central else f"{line}.")

    # 5. HISTORICAL ECHO — stated honestly, including thin history
    hist = {} if concise else (r.get("historical") or {})
    sim = int(hist.get("similar_count") or 0)
    if concise:
        pass
    elif sim >= 2:
        parts.append(f"Similar coverage preceded a same-direction move "
                     f"{int(hist.get('followed_direction') or 0)} of the last {sim} times.")
    elif sim == 1:
        parts.append("Limited history: one prior similar cluster on record.")
    else:
        parts.append("No comparable prior coverage on record yet.")

    # 6. EVIDENCE + CONFIDENCE
    ev = r.get("evidence") or {}
    conf = float(r.get("confidence") or 0.0)
    parts.append(f"Confidence: {confidence_word(conf)} ({round(conf * 100)}%) — "
                 f"{int(ev.get('articles') or 0)} articles, "
                 f"{int(ev.get('sources') or 0)} sources.")

    return " ".join(parts)


def violates_language_rules(text: str, entity_names: list[str] | None = None) -> list[str]:
    """Return any forbidden phrase present — used by tests and as a runtime guard.

    `entity_names` are masked out before scanning. Real-world names collide with the
    blocklist: the actor Will Smith trips "will ", the retailer Target trips "target",
    Rally Software trips "rally". Dropping a valid insight because a company is named
    Target is a silent failure, and the entity name is a quoted fact rather than
    something the template asserts — so it is excluded from the scan while every word
    the template itself contributes is still checked.
    """
    text = text or ""
    for name in sorted(entity_names or [], key=len, reverse=True):
        if name:
            text = re.sub(re.escape(name), " ", text, flags=re.IGNORECASE)
    low = text.lower()

    hits = [f for f in FORBIDDEN if f in low]
    hits += [w for w in FORBIDDEN_ADVICE
             if re.search(rf"\b{re.escape(w)}\b", low)]
    if PRICE_TARGET_RE.search(text):
        hits.append("price target")
    return hits
