"""
reasoning/narrative.py — template-assembled narrative (SPIE Reasoning Engine).

Pure, deterministic, stdlib-only. Every sentence is built from real fields by string
template — never generated by an LLM, so it cannot hallucinate a fact that isn't in
the data.

LANGUAGE CONTRACT (enforced by tests):
  allowed  : moved / rose / fell / coverage aligns with / connected to / preceded /
             observed / co-moved
  forbidden: will, causes, caused, predict, expect, forecast, should, and "impact"
             used as a forward claim
"""

from __future__ import annotations

# Words that would turn an observation into a causal or forward-looking claim.
FORBIDDEN = [
    "will ", "causes", "caused", "causing", "predict", "prediction", "forecast",
    "expect", "expected to", "should ", "going to", "likely to", "set to",
    "poised to", "impact on", "due to",
]


def move_words(direction: int) -> str:
    """Neutral verb for a market move."""
    return "rose" if direction > 0 else "fell" if direction < 0 else "was flat"


def signed_pct(pct: float, direction: int) -> str:
    sign = "+" if direction > 0 else "-" if direction < 0 else ""
    return f"{sign}{abs(pct):.2f}%"


def confidence_word(conf: float) -> str:
    # Bands chosen so 0.78 reads "moderate" — well-evidenced but not conclusive.
    if conf >= 0.80:
        return "high"
    if conf >= 0.5:
        return "moderate"
    if conf >= 0.3:
        return "limited"
    return "low"


def _join(items: list[str], limit: int = 3) -> str:
    """Human list: 'a, b and c' (capped)."""
    items = [i for i in items if i][:limit]
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def build_narrative(r: dict) -> str:
    """Assemble the reasoned narrative from a reasoned_insight dict.

    Only sections with real data contribute a sentence — a thin window produces a
    short honest narrative rather than padded filler.
    """
    focal = r.get("focal") or {}
    parts: list[str] = []

    # 1. THE MOVE (or the news spike, when news is focal)
    if focal.get("type") == "market_move":
        inst = focal.get("instrument", "An instrument")
        cls = focal.get("asset_class")
        pct = signed_pct(float(focal.get("move_pct") or 0.0), int(focal.get("direction") or 0))
        cls_txt = f" ({cls})" if cls else ""
        parts.append(f"{inst}{cls_txt} {move_words(int(focal.get('direction') or 0))} {pct}.")
    else:
        ents = _join(focal.get("entities") or [])
        parts.append(f"Coverage of {ents or 'these entities'} rose sharply.")

    # 2. THE NEWS BEHIND IT
    links = r.get("news_link") or []
    if links:
        articles = sum(int(l.get("article_count") or 0) for l in links)
        sources = max((int(l.get("source_count") or 0) for l in links), default=0)
        topics = _join([t for l in links for t in (l.get("entities") or [])])
        window = r.get("window_hours", 24)
        parts.append(
            f"In the preceding {window}h, {articles} article{'' if articles == 1 else 's'} "
            f"across {sources} source{'' if sources == 1 else 's'} covered "
            f"{topics or 'related entities'}.")

    # 3. CROSS-MARKET (the multi-asset payoff)
    cross = r.get("cross_market") or []
    if cross:
        movers = _join([f"{c.get('instrument')} {signed_pct(float(c.get('move_pct') or 0.0), int(c.get('direction') or 0))}"
                        for c in cross])
        n = len(cross) + 1
        parts.append(f"This coverage also aligns with {movers} — a pattern observed "
                     f"across {n} market{'' if n == 1 else 's'}.")

    # 4. CONNECTED ENTITIES
    connected = r.get("connected") or []
    if connected:
        parts.append(f"Connected to: {_join([c.get('entity') for c in connected], 4)}.")

    # 5. HISTORICAL ECHO — stated honestly, including thin history
    hist = r.get("historical") or {}
    sim = int(hist.get("similar_count") or 0)
    if sim >= 2:
        parts.append(f"Similar coverage preceded a same-direction move "
                     f"{int(hist.get('followed_direction') or 0)} of the last {sim} times.")
    elif sim == 1:
        parts.append("Limited history: one prior similar cluster on record.")
    else:
        parts.append("No comparable prior coverage on record yet.")

    # 6. EVIDENCE + CONFIDENCE
    ev = r.get("evidence") or {}
    conf = float(r.get("confidence") or 0.0)
    parts.append(f"Confidence: {confidence_word(conf)} ({round(conf * 100)}%) — "
                 f"{int(ev.get('articles') or 0)} articles, "
                 f"{int(ev.get('sources') or 0)} sources.")

    return " ".join(parts)


def violates_language_rules(text: str) -> list[str]:
    """Return any forbidden phrases present — used by tests and as a runtime guard."""
    low = (text or "").lower()
    return [f for f in FORBIDDEN if f in low]
